name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          script: ./gradlew build connectedCheck
